### ISSUE TITLE
GDPR (lack of disclaimer)

### ISSUE THREAD

**Issue by civitaseven** [vostpt/greve-transportes-perigosos#102]
It's necessary to add a GDPR  (RGPD) disclaimer to the site naodaparaabastecer.pt :
Link to VostPt disclaimer here:
https://docs.google.com/document/d/1MLdWYBOW2se4AR8BJ4PAFMFjN7i5gZUq_zwzzXGjNRw/edit?usp=sharing

**Comment by miguelantoniosantos** [comment]
Added on  #113
