### ISSUE TITLE
Wrong SEO of "Ja nao da para abastecer" 

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/greve-transportes-perigosos#103]
If I search for "Ja nao da para abastecer" 

It gives me this message that the strike is over:
https://imgur.com/a/5Spk4YY

or even:

"Após a desconvocação da greve, a nossa missão chegou ao fim. Obrigado a todos os que contribuíram com informação válida, que tantas pessoas ajudou. Obrigado a todos os que contribuíram com informação inválida, que tanto nos ajudou a aprender e a crescer. Ficam aqui os números, que falam por si. Site"

**Comment by abreulima** [comment]
It looks correctly here. 

![new](https://user-images.githubusercontent.com/34632454/62739475-d7848d00-ba02-11e9-8c16-54b735311995.png)

**Comment by miguelantoniosantos** [comment]
Unable to recreate, anyone able to recreate?

**Comment by JorgeMiguelGomes** [comment]
Apparently Google already propagated the new site. Closing this issue.
