### ISSUE TITLE
Global - Initial Laravel Initialization

### ISSUE THREAD

**Issue by miguelantoniosantos** [vostpt/greve-transportes-perigosos#11]

**Comment by miguelantoniosantos** [comment]
Solved on commit 15b05fbfbaa1d9844093fbe3c922db79857c1610.
Was unable to use a pull request as it differs a lot.

**Comment by quetzyg** [comment]
> Solved on commit [15b05fb](https://github.com/vostpt/greve-transportes-perigosos/commit/15b05fbfbaa1d9844093fbe3c922db79857c1610).
> Was unable to use a pull request as it differs a lot.

Why was that?

**Comment by miguelantoniosantos** [comment]
Creating the branch, I copied from dev/new_form by mistake, and since there was nothing compare github didn't allow to make a pull request.
