### ISSUE TITLE
[Feat]  Submissions per hour 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/greve-transportes-perigosos#114]
Implement a method to calculate total submissions + submissions per hour to be shown in a line graph within the Dashboard and main page. 
Implement a method to calculate number of reported fuel stations without _Gasolina_ / _Gasóleo_ / _GPL_ **per hour** to be shown in three different line graphs on the dashboard and main page. 

**Graphs should be made available as an iFrame as well**

**Comment by Cotemero** [comment]
@ClaudioVarandas is this complete with the pull request?
