### ISSUE TITLE
[FEAT] Internal - View Map should open in Mapbox not Waze

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/greve-transportes-perigosos#132]
On list view the option "Ver Mapa" should:
- Open in a new tab
- Open the fuel station in Mapbox view, **not Waze**

**Comment by miguelantoniosantos** [comment]
Is mapbox view consult view?

**Comment by JorgeMiguelGomes** [comment]
_Mapbox view_ =  Main display map of the website

At this time when you click "Ver no Mapa" it open a Waze page. It should open in our map, in a new tab .

**Comment by miguelantoniosantos** [comment]
#162
