### ISSUE TITLE
[Feat] Enhanced Tooltip 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/greve-transportes-perigosos#134]
On mouse over return: 
- Fuel Station Name 
- Type (Normal, REPA, REPA SOS)
- Status
**If the fuel station is** "PRIO"
- Insert link to `https://www.prio.pt/pt/postos/rede-de-postos_289.html?tab=1&type=1`

**Comment by claudiof** [comment]
I add also the last update timestamp. This way the visitor will know if the information is fresh or old.

**Comment by miguelantoniosantos** [comment]
We are unable to add links to the hover popup, we will implement with the last update timestamp

**Comment by miguelantoniosantos** [comment]
Solved on #177
