### ISSUE TITLE
[Feat] Statistics by Brand

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/greve-transportes-perigosos#136]
Context:

**Prio** is now providing official data and information to the platform. 

On the statistics page display a bar graphic just for PRIO below general availability's bars using `#3D8FAA ` for available. Name "PRIO" and linking to PRIO's homepage `https://www.prio.pt/pt/postos/rede-de-postos_289.html?tab=1&type=1`

**Comment by miguelantoniosantos** [comment]
Added stats endpoint on #144 
My job is done here, good luck @ClaudioVarandas
