### ISSUE TITLE
[Feat] Add brand filter to map 

### ISSUE THREAD

**Issue by tomahock** [vostpt/greve-transportes-perigosos#156]
Allow user to multi select a gas station brand 

<img width="314" alt="Screenshot 2019-08-12 at 18 41 39" src="https://user-images.githubusercontent.com/794581/62885472-e6d04700-bd30-11e9-8952-8279e1880028.png">

**Comment by mribeiro** [comment]
I made a rough distinct lookup by brand and there are, at least, around 60 brands. I guess it would make sense to have like the top 5 or 10, not all. What do you think?
Plus it seems there's the brand "Prio" and "Pingo Doce". Should those be merged the same?

**Comment by mribeiro** [comment]
The brands to show in the brand filter are Bxpress, Ecobrent, Oz Energia, PRIO, and Tfuel. Those are using the VOST's API to provide accurate fuel availability.
