### ISSUE TITLE
[FEAT ] add social networks

### ISSUE THREAD

**Issue by hugomvlopes** [vostpt/greve-transportes-perigosos#158]
Add facebook, twitter and instagram buttons to the website :)

**Comment by miguelantoniosantos** [comment]
@JorgeMiguelGomes where?

**Comment by JorgeMiguelGomes** [comment]
@Cotemero Before "Acesso Reservado" 
@hugomlopesviseu we need the buttons please (**in png format**)
![Screenshot 2019-08-13 at 09 06 04](https://user-images.githubusercontent.com/34355337/62925186-b2e53800-bda9-11e9-9439-20386b963406.png)

**Comment by hugomvlopes** [comment]
https://www.flaticon.com/packs/social-network-logo-collection <- this

**Comment by hugomvlopes** [comment]
three vertical dots, And download png

**Comment by miguelantoniosantos** [comment]
Solved on #179
