### ISSUE TITLE
[Feat] jump to update (ajudar) directly from "consultar" 

### ISSUE THREAD

**Issue by davipt** [vostpt/greve-transportes-perigosos#164]
When looking at the "consultar" map, it would be nice to be able to jump directly to the "ajuda", to the same fuel station, to contribute to update the status of the fuel station.

The two screens are slightly different, with the "consultar" more efficient to search for stuff, as the "ajudar" is not that clear on the brand of the station, making it quite hard, specially on a mobile, to look for a station, then have to go back to the beginning, ajudar, and search again for the same station.

**Comment by miguelantoniosantos** [comment]
@JorgeMiguelGomes

**Comment by JorgeMiguelGomes** [comment]
@davipt good suggestion and we will try to implement it. However since it's not critical we'll give it a low priority level. 
@Cotemero please assign to the team with **priority 4**
