### ISSUE TITLE
[Feat] Count searches by brand & produce graphic

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/greve-transportes-perigosos#172]
Statistics, statistics, statistics! We want data!

- Think of a way to store search strings by brand
- Program it
- Test it
-  create hourly line and bar graphic to be available on brand's BO
- Insert on each brand's BO

**Comment by miguelantoniosantos** [comment]
We are not able to do this as implement this will require direct input to the database from the client which is an entry point for an attack.
