### ISSUE TITLE
[Feat] New Dashboard as iFrame 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/greve-transportes-perigosos#174]
**INCLUDE IN MEDIA**
**Dashboard Code** 
`<style>.embed-container {position: relative; padding-bottom: 80%; height: 0; max-width: 100%;} .embed-container iframe, .embed-container object, .embed-container iframe{position: absolute; top: 0; left: 0; width: 100%; height: 100%;} small{position: absolute; z-index: 40; bottom: 0; margin-bottom: -15px;}</style><div class="embed-container"><iframe width="500" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" title="BASEMAP" src="https://arcgis.com/apps/opsdashboard/index.html#/a4890bfd60df4c07bd67c857b73b452f"></iframe></div>`

**Dashboard Description**
Uma dashboard em tempo real dos dados recolhidos no site "Já Não Dá Para Abastecer", feita em ArcGIS com o apoio da ESRI Portugal. 
Termos e condições de uso:Full Credits a VOSTPT / Esri Portugal / ArcGis

**Exemplo Dashboard**
![Screenshot 2019-08-14 at 11 42 51](https://user-images.githubusercontent.com/34355337/63015462-e77bf100-be88-11e9-9962-102111d9d2c0.png)

**CREATE NEW MENU ITEM "MORE STATS"***
Embed above code on website

**Comment by miguelantoniosantos** [comment]
Implemented on #178
