### ISSUE TITLE
[Feature] Gas Stations

### ISSUE THREAD

**Issue by VOSTPortugal** [vostpt/greve-transportes-perigosos#19]
BP can be found here: https://www.bp.com/content/dam/bp-plus/pt_pt/downloads/PDF/Lista-de-Postos-de-Abastecimento-BP.pdf 

GALP: https://estrada.galp.pt/mapa? // KML: http://www.galpenergia.com/PT/ProdutosServicos/Documents/galpfrota/Galp-Frota-Google-Earth.kml 

Repsol: https://www.repsol.com/pt_pt/fenix/BuscadorEstacionesServicio/buscador_frame.aspx?_ga=2.97863446.800368948.1556576089-1371042301.1556576089 

CEPSA: http://pertodesi.cepsa.com/ 

Vários: https://www.maisgasolina.com/lista-de-postos/ (necessário cross check)

Intermarché: https://www.google.com/maps/d/viewer?mid=1pHlEPJHf4bSfjAxUJNoPX06bTjE&ll=40.108348730661376%2C-8.544612316406301&z=8 

Direcção Geral da Energia: https://www.precoscombustiveis.dgeg.pt/ 

**What's the best way to get this data on our side? What other gas stations are there with an impact?**

**Comment by miguelantoniosantos** [comment]
No longer applicable
