### ISSUE TITLE
[Bug] Posto criado via API no PC só é visível em mobile

### ISSUE THREAD

**Issue by sr-torres** [vostpt/greve-transportes-perigosos#196]
O strangelesi criou o posto "4168 Cepsa-Côja" via https://janaodaparaabastecer.vost.pt/api/v1, via PC. 
No entanto este posto:
 a) não está visível, via PC, pelo Consultar, Ajudar ou ~panel/stations/list
 b) está visível, via mobile iOS, pelo Consultar ou Ajudar
 
 Ver screenshots com as avidências no Discord-taskforce-jndpa 15Ago07:57

**Comment by sr-torres** [comment]
Este issue manifestou-se durante 90 minutos...entretanto já está normal. 
No limite, podem fechar.

**Comment by JorgeMiguelGomes** [comment]
@sr-torres CTRL+F5 usually does it ;)
(_also, issues should be in English so that all that can contribute (basically the whole world) can understand the issue_)
