### ISSUE TITLE
[Feat] In 'Fuel Stations List' provide more geolocation info

### ISSUE THREAD

**Issue by civitaseven** [vostpt/greve-transportes-perigosos#197]
In the list of gas stations a new field with simple lat / lon (and/or link to google maps for fuel stations confirmation purposes ( because it has streetview,  - waze only has streetview in edit mode).

**Comment by JorgeMiguelGomes** [comment]
Closing issue as it's outdated by the new API version

**Comment by civitaseven** [comment]
There's another way to access the geolocation - via mapbox and backoffice
