### ISSUE TITLE
Link to LICENSE on README redirects to 404

### ISSUE THREAD

**Issue by isabelcosta** [vostpt/greve-transportes-perigosos#208]
The link on README file is pointing to file LICENSE.md instead of LICENSE (without the .md).

The generated link - https://github.com/vostpt/greve-transportes-perigosos/blob/master/LICENSE.md - makes GitHub redirect us to 404 page

**Comment by JorgeMiguelGomes** [comment]
Fixed. Thank you, @isabelcosta
