### ISSUE TITLE
[Bug] Site em branco quando tento aceder

### ISSUE THREAD

**Issue by alicescfernandes** [vostpt/greve-transportes-perigosos#241]
## Descrição
O site https://janaodaparaabastecer.vost.pt/ aparece-me a branco

## Ambiente
Browser: Google Chrome  88.0.4324.192 (Official Build) (x86_64)
OS: Mac Catalina 10.15.7

## Como reproduzir
Basta ir para o site

## Comportamento Esperado
Ver o portal

## Comportamento atual:
Página em branco, sem erros na consola

![image](https://user-images.githubusercontent.com/15971182/109433525-b16d7600-7a08-11eb-97e4-53a4bc56accd.png)

**Comment by JorgeMiguelGomes** [comment]
Olá @alicescfernandes! O projeto "JNDPA" foi um projeto temporário que não faz sentido estar online pois a informação constante no mesmo, à data que terminou a ativação da @VOSTPortugal, está neste momento totalmente desactualizada. O site cumpriu a sua função na altura. De qualquer modo obrigado por nos alertares para esta situação. 
@marcoacmaia necessitamos de fazer o redirect para a página de resumo da ativação no Blog do site principal.

**Comment by marcoacmaia** [comment]
Certo. A fazer

**Comment by JorgeMiguelGomes** [comment]
@marcoacmaia post editado em **https://vost.pt/jndpa-2019/**

**Comment by marcoacmaia** [comment]
Redirect implemented.
