### ISSUE TITLE
[Feat] Statistics and Analytics 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/greve-transportes-perigosos#85]
This is a two fold issue:

1. Use [Google Charts](https://developers.google.com/chart/interactive/docs/gallery/controls) for statistics 
2. Setup statistics **per district and county** 
3. Include Statistics and Analytics on the main page of the internal dashboard

**Comment by miguelantoniosantos** [comment]
Per district and county solved on #97

**Comment by miguelantoniosantos** [comment]
@JorgeMiguelGomes Confirm this issue is closed

**Comment by JorgeMiguelGomes** [comment]
@Cotemero Per district is not working when filtering on ArcGIS

**Comment by JorgeMiguelGomes** [comment]
@Cotemero issue not finished. However I'm closing the issue and opening a new one.
