### ISSUE TITLE
[Bug] Entries aren't reflected on map and on stats

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/greve-transportes-perigosos#87]
1. A bug is preventing entries to the map to be reflected on the map
2. A bug is preventing entries (total, day, hour) to be reflected on the main page

**Comment by miguelantoniosantos** [comment]
Entries submission fixed on #91

**Comment by JorgeMiguelGomes** [comment]
Closed!

**Comment by miguelantoniosantos** [comment]
Missing issue with stats

**Comment by miguelantoniosantos** [comment]
Solved on #92

**Comment by miguelantoniosantos** [comment]
Not Solved

**Comment by miguelantoniosantos** [comment]
Solved on #93
